---
title: "Titanic Analysis"
author: "Jonathan Chiu"
date: "November 10, 2017"
output:
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r dependencies}
library(ggplot2)
library(grid)
library(rpart)
library(rattle)
library(rpart.plot)
library(RColorBrewer)
library(randomForest)
library(party)
```

Import the train.csv and test.csv of the titanic dataset

```{r data}
setwd("~/Github/titanic")
train <- read.csv("data/train.csv")
test <- read.csv("data/test.csv")
```



```{r pressure}
str(train)
```



```{r}
train$Survived = as.factor(train$Survived)
train$Sex = as.factor(train$Sex)
```


Survived category has "0" to represent "Not Survived", and "1" to represent "Survived."

```{r}
table(train$Survived)
prop.table(table(train$Survived))
ggplot(aes(x=Survived), data = train) + geom_bar()
```



```{r}
table(train$Sex)
ggplot(aes(x=Sex), data = train) + geom_bar()
```


```{r}
ggplot(aes(x=Sex, fill=Survived), data = train) + geom_bar(position="fill")
```

